name: Go

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        go-version: ["1.24.x", "1.25.x"]

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        env:
          REALDEBRID_API_KEY: ${{ secrets.REALDEBRID_API_KEY }}
        run: go test -v ./...

  cli-build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        go-version: ["1.24.x", "1.25.x"]

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod tidy
      - name: Build CLI binary
        run: go build -o rd-test ./rd/main.go
      - name: Verify CLI binary
        run: ./rd-test
